import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "www.unco.edu" },
      { protocol: "https", hostname: "media.licdn.com" },
      { protocol: "https", hostname: "res.cloudinary.com" },
      { protocol: "https", hostname: "cdn.cfr.org" },
      { protocol: "https", hostname: "encrypted-tbn0.gstatic.com" },
      { protocol: "https", hostname: "images-na.ssl-images-amazon.com" },
      { protocol: "https", hostname: "storage.googleapis.com" },
      { protocol: "https", hostname: "upload.wikimedia.org" },
      { protocol: "https", hostname: "cz.usembassy.gov" },
      { protocol: "https", hostname: "sam.nmartmuseum.org" },
      { protocol: "https", hostname: "plus.unsplash.com" },
      { protocol: "https", hostname: "thumbs.dreamstime.com" },
      { protocol: "https", hostname: "therevealer.org" },
      { protocol: "https", hostname: "equaliteach.co.uk" },
      { protocol: "https", hostname: "static.vecteezy.com" },
      { protocol: "https", hostname: "i.pinimg.com" },
      { protocol: "https", hostname: "media.craiyon.com" },
      { protocol: "https", hostname: "external-preview.redd.it" },
      { protocol: "https", hostname: "thebookishtype.co.uk" },
      { protocol: "https", hostname: "media.philstar.com" },
      { protocol: "https", hostname: "aphrodite.gmanetwork.com" },
      { protocol: "https", hostname: "www.gaytimes.co.uk" },
      { protocol: "https", hostname: "od2-image-api.abs-cbn.com" },
      { protocol: "https", hostname: "metro.co.uk" },
      { protocol: "https", hostname: "static.wikia.nocookie.net" },
      { protocol: "https", hostname: "s.yimg.com" },
      { protocol: "https", hostname: "www.uvic.ca" },
      { protocol: "https", hostname: "images.squarespace-cdn.com" },
      { protocol: "https", hostname: "media.vanityfair.com" },
      { protocol: "https", hostname: "encrypted-tbn2.gstatic.com" },
      { protocol: "https", hostname: "i.guim.co.uk" },
      { protocol: "https", hostname: "images.theconversation.com" },
      { protocol: "https", hostname: "m.media-amazon.com" },
      { protocol: "https", hostname: "www.blackpast.org" },
      { protocol: "https", hostname: "blogs.publishersweekly.com" },
      { protocol: "https", hostname: "static01.nyt.com" },
      { protocol: "https", hostname: "humanrightsconnected.org" },
      { protocol: "https", hostname: "daily.jstor.org" },
      { protocol: "https", hostname: "cdn.britannica.com" },
      { protocol: "https", hostname: "hips.hearstapps.com" },
      { protocol: "https", hostname: "www.politico.eu" },
      { protocol: "https", hostname: "c.ndtvimg.com" },
      { protocol: "https", hostname: "images.axios.com" },
      { protocol: "https", hostname: "cloudfront-us-east-2.images.arcpublishing.com" },
      { protocol: "https", hostname: "media.zenfs.com" },
      { protocol: "https", hostname: "media.cnn.com" },
      { protocol: "https", hostname: "www.aljazeera.com" },
      { protocol: "https", hostname: "static1.squarespace.com" },
      { protocol: "https", hostname: "media-cldnry.s-nbcnews.com" },
      { protocol: "https", hostname: "images.unsplash.com" },
    ],
  },
};

export default nextConfig;
